# Generated by Django 5.2.8 on 2025-12-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventguest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventoccurrences',
            options={'ordering': ['occurrence_start']},
        ),
    ]
