# Generated by Django 5.2.8 on 2025-11-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('role', models.CharField(choices=[('student', 'Aluno'), ('professor', 'Professor'), ('admin', 'Administrador')], default='student', max_length=20, verbose_name='role')),
                ('preferred_calendar_view', models.CharField(choices=[('day', 'Dia'), ('week', 'Semana'), ('month', 'Mês'), ('year', 'Ano')], default='month', max_length=10, verbose_name='preferred_calendar_view')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
