# Generated by Django 5.2.8 on 2025-11-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='preferred_calendar_view',
            field=models.CharField(choices=[('day', 'Dia'), ('week', 'Semana'), ('month', 'Mês'), ('year', 'Ano')], default='month', max_length=10, verbose_name='preferred calendar view'),
        ),
    ]
